# Variables just for the development environment. These will override the variables in _config.yml when running jekyll serve --config _config.yml,_config.dev.yml
title             : 'Wayward Son Developers (Dev)'
url               : https://dev.waywardsondevelopers.com
environment       : development
