# Variables just for the prod environment. These will override the variables in _config.yml when running jekyll build --config _config.yml,_config.prod.yml
title                    : 'Wayward Son Developers'
url                      : https://www.waywardsondevelopers.com
environment              : production

# Sass/SCSS
sass:
  style                  : compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Disable the style guide/style check pages in dev
collections:
  styleguide:
    output               : false
