# Variables just for the prod environment. These will override the variables in _config.yml when running jekyll build --config _config.yml,_config.prod.yml
title             : 'Wayward Son Developers'
url               : https://www.waywardsondevelopers.com
environment       : production
